### PR TITLE
feat(auth): Add token based auth

### PR DESCRIPTION
**Pull request by barredterra**
- Add token based auth
- Add test
- Update README

Also, some formatting: single quotes everywhere.

@rmehta sorry for tagging you, my last PR was ignored for three months. :'D

### CODE REVIEW

**Comment by rmehta** [comment]
@barredterra sorry never saw this. Cleaned up this repo. Can you refactor this PR?

**Comment by barredterra** [comment]
Done, @rmehta

**Comment by barredterra** [comment]
@Thunderbottom , could you review this?

**Comment by Thunderbottom** [comment]
sure. ill check in the morning.

**Pull request merged**
